# Generated by Django 4.0.6 on 2023-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_stock', models.FloatField(default=0)),
                ('diesel_stock', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyElectronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo_pay', models.FloatField(default=0)),
                ('rubis_card_pay', models.FloatField(default=0)),
                ('airtel_pay', models.FloatField(default=0)),
                ('cd_pay', models.FloatField(default=0)),
                ('app_pay', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyFuelSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_price', models.FloatField(default=0)),
                ('diesel_price', models.FloatField(default=0)),
                ('pms_sales', models.FloatField(default=0)),
                ('diesels_sales', models.FloatField(default=0)),
                ('lubs', models.FloatField(default=0)),
                ('gas', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingpms1', models.FloatField(default=0)),
                ('openingpms2', models.FloatField(default=0)),
                ('openingpms3', models.FloatField(default=0)),
                ('openingpms4', models.FloatField(default=0)),
                ('openingdiesel1', models.FloatField(default=0)),
                ('openingdiesel2', models.FloatField(default=0)),
                ('openingdiesel3', models.FloatField(default=0)),
                ('openingdiesel4', models.FloatField(default=0)),
                ('closingpms1', models.FloatField(default=0)),
                ('closingpms2', models.FloatField(default=0)),
                ('closingpms3', models.FloatField(default=0)),
                ('closingpms4', models.FloatField(default=0)),
                ('closingdiesel1', models.FloatField(default=0)),
                ('closingdiesel2', models.FloatField(default=0)),
                ('closingdiesel3', models.FloatField(default=0)),
                ('closingdiesel4', models.FloatField(default=0)),
                ('pms1', models.FloatField(default=0)),
                ('pms2', models.FloatField(default=0)),
                ('pms3', models.FloatField(default=0)),
                ('pms4', models.FloatField(default=0)),
                ('diesel1', models.FloatField(default=0)),
                ('diesel2', models.FloatField(default=0)),
                ('diesel3', models.FloatField(default=0)),
                ('diesel4', models.FloatField(default=0)),
                ('pms', models.FloatField(default=0)),
                ('diesel', models.FloatField(default=0)),
                ('pms_rtt', models.FloatField(default=0)),
                ('ago_rtt', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('garbage', models.FloatField(default=0)),
                ('liquid_soap', models.FloatField(default=0)),
                ('car_fuel', models.FloatField(default=0)),
                ('food', models.FloatField(default=0)),
                ('broom', models.FloatField(default=0)),
                ('transport', models.FloatField(default=0)),
                ('airtime', models.FloatField(default=0)),
                ('price_survey', models.FloatField(default=0)),
                ('hosepipe_rubber', models.FloatField(default=0)),
                ('salary', models.FloatField(default=0)),
                ('staff_advance', models.FloatField(default=0)),
                ('water_bill', models.FloatField(default=0)),
                ('generator', models.FloatField(default=0)),
                ('shorteg', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
