# Generated by Django 4.0.6 on 2023-09-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeter',
            name='dippingago',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeter',
            name='dippingpms',
            field=models.FloatField(default=0),
        ),
    ]
