# Generated by Django 4.0.6 on 2023-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelbackend', '0002_dailymeter_dippingago_dailymeter_dippingpms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfuelsales',
            name='others',
            field=models.FloatField(default=0),
        ),
    ]
