# Generated by Django 4.0.6 on 2023-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelbackend', '0003_dailyfuelsales_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_bought', models.FloatField(default=0)),
                ('diesel_bought', models.FloatField(default=0)),
                ('pms_rate', models.FloatField(default=0)),
                ('diesel_rate', models.FloatField(default=0)),
                ('dealer_fee', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
