# Generated by Django 4.0.6 on 2023-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelbackend', '0004_buy_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_banking', models.FloatField(default=0)),
                ('station_banking', models.FloatField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
