# Generated by Django 4.0.6 on 2023-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelbackend', '0005_banking'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='difference',
            field=models.FloatField(default=0),
        ),
    ]
